### ISSUE TITLE
chore: Bring the package up to standard

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#25]
## Critères de validation 

Je peux valider que :

- [ ] Les ORCID sont renseignés dans la partie des auteurs du fichier DESCRIPTION (_**cf capture d'écran du second point**_)
- [ ] ThinkR possède le rôle `cph` dans le fichier DESCRIPTION
<img width="670" alt="Screenshot 2023-01-16 at 09 18 03" src="https://user-images.githubusercontent.com/35060481/212630662-55b964c6-9b6c-4c3b-8148-32de5ec88ae6.png">

- [ ] Le Code Of Conduct est actualisé avec une nouvelle adresse mail : 
https://github.com/ThinkR-open/checkhelper/blob/9ae2a6b39635bbe342e4a9e206987d662cf5744e/CODE_OF_CONDUCT.md
![Screenshot 2023-01-16 at 10 13 24](https://user-images.githubusercontent.com/35060481/212640947-1b29f231-73c8-4ba5-8e03-a558e1baef72.png)

- [ ] Le CI et les badges sont présents sur la page du README 
![Screenshot 2023-01-16 at 10 28 41](https://user-images.githubusercontent.com/35060481/212644064-af0a16c1-bc20-4505-89f4-bcd00f834c73.png)

![Screenshot 2023-01-16 at 10 15 07](https://user-images.githubusercontent.com/35060481/212641177-2e763f9a-ef20-49d1-bc07-cc2bb835adb0.png)

- [ ] `Config/Needs/website: ThinkR-open/thinkrtemplate` a été ajouté dans le fichier DESCRIPTION 
![Screenshot 2023-01-16 at 10 16 31](https://user-images.githubusercontent.com/35060481/212641525-6921fb2d-8bb3-454d-86ce-af750830e09c.png)

- [ ] le lien site pkgdown est dans la partie "About" de la page GitHub (_**cf capture d'écran du second point**_)
- [ ] Des Github topics sont ajoutés
![Screenshot 2023-01-16 at 10 17 44](https://user-images.githubusercontent.com/35060481/212641754-740f94d4-f9ee-4954-a163-edb097300b17.png)

- [ ] Le lien pour les bugs report est dans le fichier DESCRIPTION
![Screenshot 2023-01-16 at 10 20 21](https://user-images.githubusercontent.com/35060481/212642291-efc6733a-1e7f-43f9-838e-c49a835690ad.png)

- [ ] Ajout d'une doc générale pour le package 
![Screenshot 2023-01-16 at 10 20 56](https://user-images.githubusercontent.com/35060481/212642422-6f792759-90a4-4acc-891f-90477e3a215d.png)

- [ ] Présence d'un fichier NEWS.md
![Screenshot 2023-01-16 at 10 21 38](https://user-images.githubusercontent.com/35060481/212642571-893118a4-84f2-4edb-a50f-f05e5dacf6e5.png)

- [ ] S'assurer qu'il y a des Release + tags git en lien avec les versions du NEWS.md
![Screenshot 2023-01-16 at 10 22 14](https://user-images.githubusercontent.com/35060481/212642693-4d643260-0357-4a87-8899-9cb63fcc0537.png)

- [ ] Le pkgdown contient le template ThinkR et la bonne url pour le pkgdown
![Screenshot 2023-01-16 at 10 27 55](https://user-images.githubusercontent.com/35060481/212643903-840f021d-2be1-4550-9c30-c7976d1bd24c.png)

- [ ] Les checks sur GitHub Actions sont en succès 
![Screenshot 2023-01-16 at 10 23 28](https://user-images.githubusercontent.com/35060481/212642955-e97603f2-24b8-4533-af71-9511920a703c.png)

- [ ] Changement de licence pour du MIT
![Screenshot 2023-01-16 at 10 24 11](https://user-images.githubusercontent.com/35060481/212643100-85e17095-0422-485d-80a3-827845c2ca5a.png)

- [ ] Remplacement du fichier `devstuff_history.R` à la racine du projet pour le fichier `0-dev_history.Rmd` dans le dossier `dev`
![Screenshot 2023-01-16 at 10 25 24](https://user-images.githubusercontent.com/35060481/212643355-85133e44-b7f2-4eb1-9a85-a739c5cfe2e4.png)

## Mettre le package au standard

+ [x] Mettre les ORCID des dev dans le fichier DESCRIPTION, partie `Authors`
+ [x] Mettre ThinkR en rôle `cph` dans le fichier DESCRIPTION, partie `Authors`: `person("ThinkR", role = "cph")`
+ [x] MàJ le COC `usethis::use_code_of_conduct()`
+ [x] Mettre en place le CI et les badges sur la page du README (check, codecov)  
```r
# Doc
usethis::use_github_action_check_standard()
usethis::use_github_action("pkgdown")
usethis::use_github_action("test-coverage")
usethis::use_coverage()
usethis::use_build_ignore("_pkgdown.yml")
```
+ [x] Ajouter le badges du CRAN avec version et celui avec downloads
  -> New issue : #28 : waiting for the package on the CRAN
+ [x] Ajouter un hex 
  -> New issue : #29 
+ [x] Ajouter le template ThinkR et la bonne url pour le pkgdown 
    + Créer un fichier '_pkgdown.yml' à la racine du projet avec ce code:  
    
```yaml
template:
  package: thinkrtemplate

# Changer l'url pour celle du pkgdown 
url: https://thinkr-open.github.io/fusen/

development:
  mode: auto
```
+ [x] Ajouter `Config/Needs/website: ThinkR-open/thinkrtemplate` dans le fichier DESCRIPTION de telle sorte que l'Action pkgdown puisse fonctionner correctement (nécessite version récente -2022- de GitHub Action pour pkgdown)
    + Relancer `usethis::use_github_action("pkgdown")` au besoin en acceptant le changement complet
+ [x] Afficher le lien site pkgdown dans la partie "About" de la page GitHub
+ [x] Afficher l'URL du pkgdown + url du GitHub dans la partie `URL` du fichier description
    + e.g. pour {fusen}: https://github.com/ThinkR-open/fusen/blob/main/DESCRIPTION  
```
URL: https://thinkr-open.github.io/fusen/,
    https://github.com/Thinkr-open/fusen
```
+ [x] Ajouter le lien pour les bug report dans le fichier DESCRIPTION
    + e.g. `BugReports: https://github.com/ThinkR-open/golem/issues`
+ [x] Vérifier que ça passe les checks sur GitHub Actions
+ [x] Github topics: r-package, course-material, showcase <https://github.com/orgs/ThinkR-open/topics>
+ [x] Doc générale du package (`usethis::use_package_doc()`)
+ [x] S'assurer qu'il y a un fichier NEWS.md
+ [x] S'assurer qu'il y a des Release + tags git en lien avec les versions du NEWS.md

**Comment by statnmap** [comment]
- La fonction `covr::package_coverage()` n'a pas été récupérée du fichiers dev_history.R original
- Le fichier NEWS n'est pas à jour de la version en développement

**Comment by ArthurData** [comment]
Merci @statnmap , je viens de créer deux nouveaux tickets : 
#39 pour la version de dév
#38 pour ajouter les informations manquantes dans le fichier `dev_history`
