### ISSUE TITLE
doc: Add CRAN badges with version and downloads

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#28]
## Validation 

- [x] A badge with CRAN version
- [x] A badge with CRAN downloads  
![image](https://user-images.githubusercontent.com/21193866/218422371-e205a027-10e0-43f8-a3b7-3e2d94b3ab5f.png)

**Comment by ArthurData** [comment]
Waiting for the package available on the CRAN

**Comment by statnmap** [comment]
Validé en réunion
