### ISSUE TITLE
Check package with `checkhelper::check_as_cran`

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#47]
## Critères de validation

- [ ] La fonction `check_as_cran()` ne tombe pas lorsque ASPELL n'est pas installé sur la machine 

![Screenshot 2023-01-19 at 09 40 16](https://user-images.githubusercontent.com/35060481/213394522-449b1c0b-99ed-4599-a6fe-e3fbb0959d33.png)

- [ ] `devtools` doit être entre single quote dans DESCRIPTION

![Screenshot 2023-01-19 at 09 39 33](https://user-images.githubusercontent.com/35060481/213394340-a08be424-f3ae-434e-891e-ea5fd73dce3d.png)

- [ ] `checkhelper::check_as_cran` doit renvoyer retourner uniquement une note pour `large components` sinon 0, 0, 0

![Screenshot 2023-01-19 at 09 41 46](https://user-images.githubusercontent.com/35060481/213394859-4beee14e-ee96-4ce7-b890-b5ec8d303015.png)

## Comment technique

- [x] Mettre à jour la fonction `check_unique()`
- [x] Documenter la fonction `aspell_env_var()`
- [x] Mettre entre _single quote_ `devtools` dans DESCRIPTION
- [x] Relancer la fonction `check_as_cran`
- [x] Relancer les fonctions #31 pour s'assurer, notamment, des éventuels tags manquants

**Comment by statnmap** [comment]
Je valide. J'ouvre tout de même une nouvelle issue pour la description parce que c'est un peu plus compliqué que ça :smile: : https://github.com/ThinkR-open/checkhelper/issues/51
