### ISSUE TITLE
Check package locally: check urls

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#48]
## Critères de validation

- [ ] Check URL are correct

![Image](https://user-images.githubusercontent.com/35060481/213157750-0cccd814-521e-482d-90c6-06ce6b5b60ac.png)

## Comment 

```
# Check URL are correct
# remotes::install_github("r-lib/urlchecker")
urlchecker::url_check()
urlchecker::url_update()
```

**Comment by statnmap** [comment]
Je valide
