### ISSUE TITLE
Mettre à jour dev_history avec check_clean_userspace

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#56]
## Critères de validation

- [x] La partie de dev_history pour les changed file doit pouvoir être remplacé par le contenu de la fonction `check_clean_userspace`
![Screenshot 2023-01-25 at 17 16 02](https://user-images.githubusercontent.com/35060481/214616571-3f080006-38a9-4efc-a822-453ddb7afd13.png)
tion de la PR #24

**Comment by statnmap** [comment]
Je valide
