### ISSUE TITLE
Clean package after checks 

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#60]
## Critère de validation 

- [x] La fonction `check_clean_userspace` doit m'indiquer le package est "clean" après son exécution
    + This is ok for the moment, as all that keeps at the end of the process is in the Tmp directory of the session
![image](https://user-images.githubusercontent.com/21193866/218413444-d337f678-3fc4-4df1-bda2-775785b75f33.png)

## Comment technique 

- [ ] Ajouter `unlink()` à toutes les fonctions qui réalisent un check

**Comment by statnmap** [comment]
On valide à deux
