### ISSUE TITLE
Dernière ligne droite pour la soumission au CRAN

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#61]
## Critère de validation 

Le package a déjà été testé, je constate que :
- [x] Aucune nouvelle erreur ou warning ne survient suite aux différents tests du package
    - I answered "Yes" to all questions of `devtools::release()` 

## Comment technique 

- [ ] réexecuter le contenu et les fonctions de dev/dev_history.Rmd

**Comment by statnmap** [comment]
Je clos pour gérer la suite ici: https://github.com/ThinkR-open/checkhelper/issues/69
