### ISSUE TITLE
As a dev, I would like to see the function `check_as_cran` tested successfully

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#65]
## Validation criteria

- [x] The function must be successful during CRAN tests

- [x] This Ncpus were commented   
_before_   
![image](https://user-images.githubusercontent.com/21193866/218517839-01b649a2-156d-4a95-abd1-8dd647bf0d83.png)  
_after_  
![image](https://user-images.githubusercontent.com/21193866/219705359-25383447-aee9-4cb9-9d74-92cfffdfa0ad.png)

## How to?

Actually the function failed : 

![image](https://user-images.githubusercontent.com/35060481/218514001-5e0fb687-c2be-45e7-895f-25bc1a18e63c.png)

**Comment by statnmap** [comment]
The tests did not fail in Incoming CRAN checks.
